networks:
  dev:

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - production_db_volume:/var/lib/mysql
    env_file:
      - .live.env
  backend:
    build:
      context: ./Backend/back
      dockerfile: Dockerfile
    networks:
      - dev
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend/front
      dockerfile: Dockerfile
    networks:
      - dev
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      # - backend
      - frontend
    networks:
      - dev

  
  